### ISSUE TITLE
Update Opencore

### ISSUE THREAD

**Issue by retrohog** [Howardnm/HP-OMEN-3-Hackintosh-Bigsur-Monterey#1]
Hi, I do have same laptop and almost same specs if you don't mind could you please update it to with latest Opencore and optimise the battery thing to 100% you're great sir i was literally trying to fix my battery from last 2 months and can we upgrade to Monterey?

**Comment by Howardnm** [comment]
I just modified it according to t-shao. I didn't have the ability to make a lot of changes. This EFI does not support Monterey and no one has been able to optimize the battery. I am so sorry.

**Comment by retrohog** [comment]
Okay no worries but you did really great 😊
