### ISSUE TITLE
Updated to OC 0.7.7 with Monterey 12.2 Fully working

### ISSUE THREAD

**Issue by retrohog** [Howardnm/HP-OMEN-3-Hackintosh-Bigsur-Monterey#2]
Hi would you like to try my EFI for OMEN working in latest Monterey 12.2. System updates working battery stats works fully till 100% but I didn't get any idea to enable battery health anyways it gives around 4 hours of screen on time while surfing or just normal work so maybe that's great. If you would like to give it a try letmme know.

Thanks

**Comment by Howardnm** [comment]
thank you . I'll try

**Comment by Howardnm** [comment]
After several days of testing, the battery showed normal. I have made some modifications to EFI. Added skins in Opencore. you can try my EFI.
I've published it in this library.

Thank you so much!

**Comment by retrohog** [comment]
Tried now didn't boot stuck at loading. Checking what to fix if i could find it.

Thanks for your work. Could you please mention the changes you did it will be easy for me debug issues.
